version: '2.1'
orbs:
  mvnw: ayte/mvnw@0.1.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: /tmp/workspace
    steps:
      - checkout
      - mvnw/circle:
          command: -B install
      - persist_to_workspace:
          root: /tmp/workspace
          paths: ['*', '**/*']
  validate-allure:
    docker:
      - image: circleci/openjdk:8
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - mvnw/circle:
          command: allure:report
      - persist_to_workspace:
          root: /tmp/workspace
          paths: ['*', '**/*']
  snapshot:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          echo 'Package: libassuan0' | sudo tee /etc/apt/preferences.d/libassuan0
          echo 'Pin: release n=stretch-backports' | sudo tee -a /etc/apt/preferences.d/libassuan0
          echo 'Pin-Priority: 1000' | sudo tee -a /etc/apt/preferences.d/libassuan0
      - run: sudo apt-get install gpg gpg-agent
      - run: echo "$GPG_SECRET_KEY" | base64 -d > /tmp/key
      - run: echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key
      - run: rm /tmp/key
      - run: sudo ln -s $(which gpg) /usr/local/bin/gpg2
      - mvnw/circle:
          command: -B -pl '!src/validator' package gpg:sign nexus-staging:deploy
  release:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          echo 'Package: libassuan0' | sudo tee /etc/apt/preferences.d/libassuan0
          echo 'Pin: release n=stretch-backports' | sudo tee -a /etc/apt/preferences.d/libassuan0
          echo 'Pin-Priority: 1000' | sudo tee -a /etc/apt/preferences.d/libassuan0
      - run: sudo apt-get install gpg gpg-agent
      - run: echo "$GPG_SECRET_KEY" | base64 -d > /tmp/key
      - run: echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key
      - run: rm /tmp/key
      - run: sudo ln -s $(which gpg) /usr/local/bin/gpg2
      - mvnw/circle:
          command: -B -pl '!src/validator' package gpg:sign nexus-staging:deploy nexus-staging:release

workflows:
  version: '2.1'
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - validate-allure:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - snapshot:
          requires:
            - build
            - validate-allure
          context: sonatype.org
          filters:
            branches:
              only: /release\/.*/
            tags:
              ignore: /.*/
      - release:
          requires:
            - build
            - validate-allure
          context: sonatype.org
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d+\.\d+\.\d+/
